# Generated by Django 4.2.11 on 2025-11-04 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionenvio',
            options={'verbose_name_plural': 'Direcciones de envío'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='region',
            field=models.CharField(default='Maule', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido'),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
