# Generated by Django 4.2.26 on 2025-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
