# Generated by Django 4.2.26 on 2025-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='producto',
            name='provincia',
            field=models.CharField(default='Maule', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='region',
            field=models.CharField(default='Talca', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
    ]
