# Generated by Django 4.2.26 on 2025-11-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_producto_ciudad_producto_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='region',
        ),
        migrations.AddField(
            model_name='producto',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
