# Generated by Django 4.2.26 on 2025-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_producto_provincia_producto_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_retiro',
            field=models.TextField(blank=True, default='Av. Vicuña Mackenna 1234, La Florida, Provincia de Santiago, Región Metropolitana'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_atencion',
            field=models.TextField(blank=True, default='Lunes a Viernes 9:00 - 18:00\nSábados: 10:00 - 14:00'),
        ),
    ]
