# Generated by Django 4.2.26 on 2025-11-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usuario_direccion_retiro_usuario_horario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
