# Generated by Django 4.2.26 on 2025-11-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pedido_estado_pago_pedido_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='ganancia_vendedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
