# Generated by Django 4.2.26 on 2025-11-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_detallepedido_ganancia_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
