# Generated by Django 4.2.26 on 2025-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_producto_vendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion_retiro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='horario_atencion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
